import { Inter } from 'next/font/google';
import Cabecalho from '@/components/header/page';
import Rodape from '@/components/footer/page';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Saude',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Cabecalho />
        {children}
        <Rodape />
      </body>
    </html>
  );
}
